export const IPC_CHANNELS = {
  windowControl: "spira:window-control",
  connectionStatusGet: "connection-status:get",
  settingsGet: "settings:get",
  settingsSet: "settings:set",
  conversation: {
    recentGet: "conversation:recent:get",
    list: "conversation:list",
    get: "conversation:get",
    search: "conversation:search",
    markViewed: "conversation:mark-viewed",
    archive: "conversation:archive",
  },
  youTrack: {
    statusGet: "youtrack:status:get",
    ticketsList: "youtrack:tickets:list",
    projectsSearch: "youtrack:projects:search",
    stateMappingSet: "youtrack:state-mapping:set",
  },
  projects: {
    repoMappingsGet: "projects:mappings:get",
    workspaceRootSet: "projects:workspace-root:set",
    repoMappingSet: "projects:mapping:set",
  },
  missions: {
    runsGet: "missions:runs:get",
    start: "missions:ticket-run:start",
    sync: "missions:ticket-run:sync",
    workStart: "missions:ticket-run:work:start",
    workContinue: "missions:ticket-run:work:continue",
    workCancel: "missions:ticket-run:work:cancel",
    complete: "missions:ticket-run:complete",
    proofsGet: "missions:ticket-run:proofs:get",
    timelineGet: "missions:ticket-run:timeline:get",
    repoIntelligenceGet: "missions:ticket-run:repo-intelligence:get",
    repoIntelligenceApprove: "missions:ticket-run:repo-intelligence:approve",
    proofRun: "missions:ticket-run:proof:run",
    proofArtifactRead: "missions:ticket-run:proof-artifact:read",
    proofManualReviewSet: "missions:ticket-run:proof:manual-review:set",
    proofManualReviewClear: "missions:ticket-run:proof:manual-review:clear",
    proofRulesList: "missions:proof-rules:list",
    proofRulesUpsert: "missions:proof-rules:upsert",
    proofRulesDelete: "missions:proof-rules:delete",
    delete: "missions:ticket-run:delete",
    reviewSnapshotGet: "missions:ticket-run:review-snapshot:get",
    gitStateGet: "missions:ticket-run:git-state:get",
    submoduleGitStateGet: "missions:ticket-run:submodule-git-state:get",
    commitDraftGenerate: "missions:ticket-run:commit-draft:generate",
    commitDraftSet: "missions:ticket-run:commit-draft:set",
    submoduleCommitDraftGenerate: "missions:ticket-run:submodule:commit-draft:generate",
    submoduleCommitDraftSet: "missions:ticket-run:submodule:commit-draft:set",
    commit: "missions:ticket-run:commit",
    submoduleCommit: "missions:ticket-run:submodule:commit",
    publish: "missions:ticket-run:publish",
    submodulePublish: "missions:ticket-run:submodule:publish",
    push: "missions:ticket-run:push",
    submodulePush: "missions:ticket-run:submodule:push",
    pullRequestCreate: "missions:ticket-run:pull-request:create",
    submodulePullRequestCreate: "missions:ticket-run:submodule:pull-request:create",
    servicesGet: "missions:ticket-run:services:get",
    serviceStart: "missions:ticket-run:service:start",
    serviceStop: "missions:ticket-run:service:stop",
  },
  dialog: {
    pickDirectory: "dialog:pick-directory",
  },
  shell: {
    openExternal: "shell:open-external",
  },
  runtimeConfig: {
    get: "runtime-config:get",
    set: "runtime-config:set",
  },
  upgrade: {
    response: "upgrade:respond",
  },
  rendererFatal: "renderer:fatal",
} as const;
